### ISSUE TITLE
AutoMediation doesn't work for nested views

### ISSUE THREAD

**Issue by cmandlbaur** [s9tpepper/robotlegs-starling-plugin#5] opened 2012-07-08 08:10 UTC
I've tracked the issue down to the fact that Starling doesn't bubble ADDED_TO_STAGE, ADDED, REMOVED, REMOVED_FROM_STAGE events. 

That coupled with the StarlingMediatorMap expecting all the events to be coming through the contextView breaks automediation if you add a DisplayObject to a DisplayObjectContainer already on the stage.

The solution I've come up with to work around it for now is to added a listen(dispatcher:DisplayObjectContainer) function on the StarlingMediatorMap. This then calls a modified addListeners passing in the dispatcher.

A bit more manual than I'd like but it seems to work.

**Comment by dreammonkey** [comment] 2012-07-20 21:38
hi cmandlbaur, I just came across this issue too and I must say it's a real party crasher :(

Could you maybe post some code on exactly what it is you came up with to fix this ?
Perhaps you have a fork we could use ?

Much appreciated !

**Comment by cmandlbaur** [comment] 2012-07-20 21:45
Did fork here:
https://github.com/cmandlbaur/robotlegs-starling-plugin.git

**Comment by dreammonkey** [comment] 2012-07-20 22:25
thanks ! you saved my party ;)

btw: I just made a fork of Stray's SignalMediator solution to make it work with the Starling version here:
https://github.com/dreammonkey/robotlegs-utilities-SignalMediator

Not sure if it's fully working though...

**Comment by s9tpepper** [comment] 2012-07-27 01:17
I thought they fixed the bubbling of those events in Starling already. 

@cmandlbaur Is there code you want to maybe Pull Request back into my branch?

**Comment by cmandlbaur** [comment] 2012-08-02 20:12
Sorry will make a request now, but as I said its a bit more manual than I would prefer but its works :).

**Comment by dreammonkey** [comment] 2012-08-02 20:18
It does in fact work, but I noticed that you have to watch out with the order of the Mediator bootstrapping: i.e. children before parents... not sure why though... :(

**Comment by s9tpepper** [comment] 2012-08-11 18:41
Closing this issue, its being tracked in the PR here: https://github.com/s9tpepper/robotlegs-starling-plugin/pull/7

**Closed as completed by s9tpepper** 2012-08-11 18:41 UTC

**Comment by plippy** [comment] 2012-11-15 11:27
I'm having trouble using this workaround.

I've created a flash builder library project, included the src, included the following in libs:
     robotlegs-framework-v1.5.2.swc
     starling-v1.2.swc
     SwiftSuspenders-v1.6.0.swc

When I use the output swc from that lib project in another project, I get the following error:
"
TypeError: Error #1034: Type Coercion failed: cannot convert  to org.robotlegs.core.IReflector.
    at org.robotlegs.mvcs::StarlingContext/get reflector()[C:\Users\Paul\Desktop\starlingMediatorFix\src\org\robotlegs\mvcs\StarlingContext.as:215]
"
Why does the error contain the path to where I originally made the swc?

**Comment by s9tpepper** [comment] 2012-11-15 15:51
SWCs maintain the path of the file locations when the files were compiled into SWC form. You'll see this in other third party libraries as well when an error originates in the code of a particular SWC. I'm not really sure why you're getting this error, its a little hard to guess what the problem is. It seems like StarlingContext's reflector getter has an incompatibility with org.robotlegs.core.IReflector for some reason. It might be the reference of IReflector in starling-v1.2.swc is conflicting with the version in robotlegs-framework-v1.5.2.swc, but I'm really just guessing at this point.
